version: "3"
services:
  zk01:
    image: zookeeper:3.4.10
    container_name: zk01
    privileged: true
    volumes:
      - /usr/local/zookeeper01/data:/data
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk01:2888:3888 server.2=zk02:2888:3888 server.3=zk03:2888:3888:observer

  zk02:
    image: zookeeper:3.4.10
    container_name: zk02
    privileged: true
    volumes:
      - /usr/local/zookeeper02/data:/data
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk01:2888:3888 server.2=zk02:2888:3888 server.3=zk03:2888:3888:observer
  zk03:
    image: zookeeper:3.4.10
    container_name: zk03
    privileged: true
    volumes:
      - /usr/local/zookeeper03/data:/data
    ports:
      - "2184:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk01:2888:3888 server.2=zk02:2888:3888 server.3=zk03:2888:3888:observer
      peerType: observer
